/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TotalControl_TotalControl */

#ifndef _Included_TotalControl_TotalControl
#define _Included_TotalControl_TotalControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TotalControl_TotalControl
 * Method:    TCopen
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TotalControl_TotalControl_TCopen
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     TotalControl_TotalControl
 * Method:    TCsetGamma0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_TotalControl_TotalControl_TCsetGamma0
  (JNIEnv *, jclass);

/*
 * Class:     TotalControl_TotalControl
 * Method:    TCsetGamma1
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_TotalControl_TotalControl_TCsetGamma1
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     TotalControl_TotalControl
 * Method:    TCsetGamma9
 * Signature: (IIFIIFIIF)I
 */
JNIEXPORT jint JNICALL Java_TotalControl_TotalControl_TCsetGamma9
  (JNIEnv *, jclass, jint, jint, jfloat, jint, jint, jfloat, jint, jint, jfloat);

/*
 * Class:     TotalControl_TotalControl
 * Method:    TCinitStats
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TotalControl_TotalControl_TCinitStats
  (JNIEnv *, jclass);

/*
 * Class:     TotalControl_TotalControl
 * Method:    TCrefresh0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_TotalControl_TotalControl_TCrefresh0
  (JNIEnv *, jclass);

/*
 * Class:     TotalControl_TotalControl
 * Method:    TCrefresh1
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_TotalControl_TotalControl_TCrefresh1
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     TotalControl_TotalControl
 * Method:    TCrefresh2
 * Signature: ([I[I)I
 */
JNIEXPORT jint JNICALL Java_TotalControl_TotalControl_TCrefresh2
  (JNIEnv *, jclass, jintArray, jintArray);

/*
 * Class:     TotalControl_TotalControl
 * Method:    TCsetStrandPin
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_TotalControl_TotalControl_TCsetStrandPin
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     TotalControl_TotalControl
 * Method:    TCclose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TotalControl_TotalControl_TCclose
  (JNIEnv *, jclass);

/*
 * Class:     TotalControl_TotalControl
 * Method:    TCprintStats
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TotalControl_TotalControl_TCprintStats
  (JNIEnv *, jclass);

/*
 * Class:     TotalControl_TotalControl
 * Method:    TCprintError
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_TotalControl_TotalControl_TCprintError
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
